// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz-H7WLkw6aozQU7GgOcfR-1LeDfK_anE',
    appId: '1:538887897528:web:76b7cef4e8330b9b1ecf4d',
    messagingSenderId: '538887897528',
    projectId: 'midway-mapper',
    authDomain: 'midway-mapper.firebaseapp.com',
    storageBucket: 'midway-mapper.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjMwGySl-CjjD03vzoBRUf3XBRNpY9ITw',
    appId: '1:538887897528:android:2526288f2f7dfb101ecf4d',
    messagingSenderId: '538887897528',
    projectId: 'midway-mapper',
    storageBucket: 'midway-mapper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPY5q3BXYSiQTcfqw3hpTN93U_IN93P9g',
    appId: '1:538887897528:ios:9cd19db71d5d8cfc1ecf4d',
    messagingSenderId: '538887897528',
    projectId: 'midway-mapper',
    storageBucket: 'midway-mapper.appspot.com',
    iosBundleId: 'com.danielappelcs4750.midwaymapper.flutterCs4750MidwayMapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPY5q3BXYSiQTcfqw3hpTN93U_IN93P9g',
    appId: '1:538887897528:ios:092d5fbdefca776e1ecf4d',
    messagingSenderId: '538887897528',
    projectId: 'midway-mapper',
    storageBucket: 'midway-mapper.appspot.com',
    iosBundleId: 'com.danielappelcs4750.midwaymapper.flutterCs4750MidwayMapper.RunnerTests',
  );
}
